### ISSUE TITLE
TODO: 世界设置完善

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#271]
删除以下设置：

- [x] 世界生成—世界—生物群落
- [x] 世界生成—世界—出生点
- [x] 世界生成—世界—试金石
- [ ] 
- [x] 世界规则—全局—活动
- [x] 世界规则—全局—春
- [x] 世界规则—全局—夏
- [x] 世界规则—全局—秋
- [x] 世界规则—全局—冬
- [x] 世界规则—全局—皮弗娄牛发情频率

- [x] 世界规则—活动（全部移除，并且让代码里世界规则中的    世界规则—全局—活动    为none）
- [ ] 
- [x] 世界规则—冒险家—季节起始物品
- [x] 世界规则—冒险家—启蒙怪兽
- [ ] 
- [x] 世界规则—资源再生（全部移除，并且让代码里世界规则中的    世界规则—资源再生—再生速度    为none，而且记得把代码里的芦笋再生删了，再生相关的以后再说）

将以下设置转移至  世界生成—资源

- [x] 世界生成—世界—遗物
- [x] 世界生成—世界—遗迹雕像
